In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_excel('Sample.xlsx')
df

/opt/anaconda3/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Fiscal Quarter ID,Fiscal Period ID,Sales Level 1,Sales Level 2,Sales Level 3,Internal Business Entity Description,Internal Sub Business Entity Description,Corporate Bookings Flag,Organization Code,Technology Group,...,Product Classification,Software Type,Revenue Recognition Flag,Accounting Rule,Product Family,Txn Net Price Indicator,XCAT Flag,Business Model,Org Category,Product Bookings Net
0,2025Q2,202504.0,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Perpetual,Y,NaN,HCIPPSW,=,N,Physical Delivery,Adj. Org,-8.006000e+01
1,2025Q2,202504.0,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,On-Premise Subscription,Y,NaN,UCSHX,=,N,Physical Delivery,Adj. Org,-1.077467e+04
2,2025Q2,202504.0,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HCIPS,=,N,Non Factory,Adj. Org,-7.543200e+02
3,2025Q2,202504.0,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HCISW,=,N,Non Factory,Adj. Org,-9.439980e+03
4,2025Q2,202504.0,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HXDP,=,N,Non Factory,Adj. Org,-3.830000e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147355,2025Q2,202504.0,WW Distribution,WW Distribution-MISCL2,WW Distribution-MISCL3,Wireless,Ent. - Wireless,N,MSJ,ENGTG,...,Software,On-Premise Subscription,Y,Immediate,AIRDNAC,Y,N,Traditional MSJ,Non Factory Org,0.000000e+00
147356,2025Q2,202504.0,WW Distribution,WW Distribution-MISCL2,WW Distribution-MISCL3,Wireless,Ent. - Wireless,N,MSJ,ENGTG,...,Software,On-Premise Subscription,Y,Immediate,AIRDNCT,Y,N,Traditional MSJ,Non Factory Org,0.000000e+00
147357,2025Q2,202504.0,WW Distribution,WW Distribution-MISCL2,WW Distribution-MISCL3,Wireless,Ent. - Wireless,N,NCB,ENGTG,...,Hardware,UNKNOWN,Y,Immediate,C980040,Y,N,Physical Delivery,Non Factory Org,-1.927834e+04
147358,2025Q2,202504.0,WW Distribution,WW Distribution-MISCL2,WW Distribution-MISCL3,Wireless,Ent. - Wireless,N,SJM,ENGTG,...,Software,On-Premise Perpetual,Y,Immediate,AIRCTB2,Y,N,Electronic,Non Factory Org,-3.114600e+03
147359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Sum:,NaN,NaN,2.671806e+09

In [5]:
# Filter data with 2 conditions
#filtered_data_1 = df[df['Txn Net Price Indicator'].isin(['=', 'Y'])& df['Corporate Bookings Flag']=='Y']

# Create the first pivot table (for Category A)
#pivot_1 = pd.pivot_table(filtered_data_1,index='Business Model',columns='Fiscal Quarter ID',values='Product Bookings Net',aggfunc='sum')
    

# Save the pivot table to an Excel file
#with pd.ExcelWriter('filtered_pivot_category.xlsx', engine='xlsxwriter') as writer:
#    pivot_1.to_excel(writer, sheet_name='pivot1')
    
#print("Filtered pivot table for pivot1 created and saved successfully.")

Filtered pivot table for pivot1 created and saved successfully.

In [4]:
pivot=df.pivot_table(index=['Business Model'],
                    values=['Product Bookings Net'],
                    aggfunc='sum')

print (pivot)

                   Product Bookings Net
Business Model
Acquisition                3.977391e+08
Electronic                 2.208989e+07
NON FACTORY                2.395364e+07
Non Factory                6.446795e+08
Physical Delivery          1.459114e+09
Traditional MSJ            1.259692e+08
XCAT-MSJ                  -1.739578e+06

In [5]:
# Save the pivot table to an Excel file
with pd.ExcelWriter('pivot_creation.xlsx', engine='xlsxwriter') as writer:
    pivot.to_excel(writer, sheet_name='pivot1')

Pivot table- used to summarize and aggregate data inside dataframe
Pivot can't do that. 
To get the Grand total use and Subtotal, Margins=True

In [10]:
table = pd.pivot_table(df, values='Product Bookings Net',columns='Fiscal Quarter ID',
                       index='Business Model', aggfunc='sum',margins=True)
table

Fiscal Quarter ID        2025Q2           All
Business Model
Acquisition        3.977391e+08  3.977391e+08
Electronic         2.208989e+07  2.208989e+07
NON FACTORY        2.395364e+07  2.395364e+07
Non Factory        6.446795e+08  6.446795e+08
Physical Delivery  1.459114e+09  1.459114e+09
Traditional MSJ    1.259692e+08  1.259692e+08
XCAT-MSJ          -1.739578e+06 -1.739578e+06
All                2.671806e+09  2.671806e+09

In [11]:
# Save the pivot table to an Excel file
with pd.ExcelWriter('pivot_creation2.xlsx', engine='xlsxwriter') as writer:
    table.to_excel(writer, sheet_name='pivot1')