In [1]:
import pandas as pd
import numpy as np

In [2]:
dfb= pd.read_excel('bank statement.xlsx')
dfb

        Date  Bank Amount (INR) Bank Reference           Bank Description
0 2025-05-01              50000      REF123456              Salary Credit
1 2025-05-03              -5000      REF345678    Electricity Bill - Tata
2 2025-05-05              -1200      REF120045        Phone Bill - Airtel
3 2025-05-08             -10000      REF784512         Rent Payment - May
4 2025-05-15              75000      REF741258     Client Payment Inv#205
5 2025-05-21              -1500      REF698745     Internet Charges - ACT
6 2025-05-25              -8000      REF963258  Office Supplies - Staples
7 2025-05-30              -2500      REF487512  Zomato Food Reimbursement

In [3]:
dfb['Reference']=dfb['Bank Reference']
dfb

,Date,Bank Amount (INR),Bank Reference,Bank Description,Reference
0,2025-05-01,50000,REF123456,Salary Credit,REF123456
1,2025-05-03,-5000,REF345678,Electricity Bill - Tata,REF345678
2,2025-05-05,-1200,REF120045,Phone Bill - Airtel,REF120045
3,2025-05-08,-10000,REF784512,Rent Payment - May,REF784512
4,2025-05-15,75000,REF741258,Client Payment Inv#205,REF741258
5,2025-05-21,-1500,REF698745,Internet Charges - ACT,REF698745
6,2025-05-25,-8000,REF963258,Office Supplies - Staples,REF963258
7,2025-05-30,-2500,REF487512,Zomato Food Reimbursement,REF487512

In [4]:
dfg=pd.read_excel('general ledger.xlsx')
dfg

        Date  GL Amount (INR) GL Reference                GL Description
0 2025-05-01            50000    REF123456            Salary A/c – April
1 2025-05-03            -5000    REF345678          Power Utility - Tata
2 2025-05-05            -1250    REF120045               Airtel Recharge
3 2025-05-08           -10000    REF784512         Rent Transfer for May
4 2025-05-15            75000    REF741258  Client Receipt – Invoice 205
5 2025-05-21            -1500    REF698745      Broadband – ACT Fibernet
6 2025-05-25            -7800    REF963258         Supplies – Stationery
7 2025-05-30            -2500    REF487512           Zomato – Team Lunch
8 2025-05-31            -3000    REF159357         Miscellaneous Expense

In [5]:
dfg['Reference']=dfg['GL Reference']
dfg

,Date,GL Amount (INR),GL Reference,GL Description,Reference
0,2025-05-01,50000,REF123456,Salary A/c – April,REF123456
1,2025-05-03,-5000,REF345678,Power Utility - Tata,REF345678
2,2025-05-05,-1250,REF120045,Airtel Recharge,REF120045
3,2025-05-08,-10000,REF784512,Rent Transfer for May,REF784512
4,2025-05-15,75000,REF741258,Client Receipt – Invoice 205,REF741258
5,2025-05-21,-1500,REF698745,Broadband – ACT Fibernet,REF698745
6,2025-05-25,-7800,REF963258,Supplies – Stationery,REF963258
7,2025-05-30,-2500,REF487512,Zomato – Team Lunch,REF487512
8,2025-05-31,-3000,REF159357,Miscellaneous Expense,REF159357

# Keeping all the records from Bank statement and GL in 1 file using merge function and Reference column is the key

In [6]:
df1=pd.merge(dfb,dfg,on='Reference',how='outer',suffixes=('_bank','_gl'))
df1

,Date_bank,Bank Amount (INR),Bank Reference,Bank Description,Reference,Date_gl,GL Amount (INR),GL Reference,GL Description
0,2025-05-01,50000.0,REF123456,Salary Credit,REF123456,2025-05-01,50000,REF123456,Salary A/c – April
1,2025-05-03,-5000.0,REF345678,Electricity Bill - Tata,REF345678,2025-05-03,-5000,REF345678,Power Utility - Tata
2,2025-05-05,-1200.0,REF120045,Phone Bill - Airtel,REF120045,2025-05-05,-1250,REF120045,Airtel Recharge
3,2025-05-08,-10000.0,REF784512,Rent Payment - May,REF784512,2025-05-08,-10000,REF784512,Rent Transfer for May
4,2025-05-15,75000.0,REF741258,Client Payment Inv#205,REF741258,2025-05-15,75000,REF741258,Client Receipt – Invoice 205
5,2025-05-21,-1500.0,REF698745,Internet Charges - ACT,REF698745,2025-05-21,-1500,REF698745,Broadband – ACT Fibernet
6,2025-05-25,-8000.0,REF963258,Office Supplies - Staples,REF963258,2025-05-25,-7800,REF963258,Supplies – Stationery
7,2025-05-30,-2500.0,REF487512,Zomato Food Reimbursement,REF487512,2025-05-30,-2500,REF487512,Zomato – Team Lunch
8,NaT,NaN,NaN,NaN,REF159357,2025-05-31,-3000,REF159357,Miscellaneous Expense

# Check whether Amount is same for the matched  reference nos.

In [7]:
df1['Additional comments'] = df1.apply(
    lambda x: "Amount Matched" if x['Bank Amount (INR)'] == x['GL Amount (INR)'] else "Amount Not Matched",
    axis=1
)

In [8]:
df1

,Date_bank,Bank Amount (INR),Bank Reference,Bank Description,Reference,Date_gl,GL Amount (INR),GL Reference,GL Description,Additional comments
0,2025-05-01,50000.0,REF123456,Salary Credit,REF123456,2025-05-01,50000,REF123456,Salary A/c – April,Amount Matched
1,2025-05-03,-5000.0,REF345678,Electricity Bill - Tata,REF345678,2025-05-03,-5000,REF345678,Power Utility - Tata,Amount Matched
2,2025-05-05,-1200.0,REF120045,Phone Bill - Airtel,REF120045,2025-05-05,-1250,REF120045,Airtel Recharge,Amount Not Matched
3,2025-05-08,-10000.0,REF784512,Rent Payment - May,REF784512,2025-05-08,-10000,REF784512,Rent Transfer for May,Amount Matched
4,2025-05-15,75000.0,REF741258,Client Payment Inv#205,REF741258,2025-05-15,75000,REF741258,Client Receipt – Invoice 205,Amount Matched
5,2025-05-21,-1500.0,REF698745,Internet Charges - ACT,REF698745,2025-05-21,-1500,REF698745,Broadband – ACT Fibernet,Amount Matched
6,2025-05-25,-8000.0,REF963258,Office Supplies - Staples,REF963258,2025-05-25,-7800,REF963258,Supplies – Stationery,Amount Not Matched
7,2025-05-30,-2500.0,REF487512,Zomato Food Reimbursement,REF487512,2025-05-30,-2500,REF487512,Zomato – Team Lunch,Amount Matched
8,NaT,NaN,NaN,NaN,REF159357,2025-05-31,-3000,REF159357,Miscellaneous Expense,Amount Not Matched

# Find out the recurring patterns

In [9]:
df1['Bank Description']=df1['Bank Description'].str.lower()
df1['GL Description']=df1['GL Description'].str.lower()
df1

,Date_bank,Bank Amount (INR),Bank Reference,Bank Description,Reference,Date_gl,GL Amount (INR),GL Reference,GL Description,Additional comments
0,2025-05-01,50000.0,REF123456,salary credit,REF123456,2025-05-01,50000,REF123456,salary a/c – april,Amount Matched
1,2025-05-03,-5000.0,REF345678,electricity bill - tata,REF345678,2025-05-03,-5000,REF345678,power utility - tata,Amount Matched
2,2025-05-05,-1200.0,REF120045,phone bill - airtel,REF120045,2025-05-05,-1250,REF120045,airtel recharge,Amount Not Matched
3,2025-05-08,-10000.0,REF784512,rent payment - may,REF784512,2025-05-08,-10000,REF784512,rent transfer for may,Amount Matched
4,2025-05-15,75000.0,REF741258,client payment inv#205,REF741258,2025-05-15,75000,REF741258,client receipt – invoice 205,Amount Matched
5,2025-05-21,-1500.0,REF698745,internet charges - act,REF698745,2025-05-21,-1500,REF698745,broadband – act fibernet,Amount Matched
6,2025-05-25,-8000.0,REF963258,office supplies - staples,REF963258,2025-05-25,-7800,REF963258,supplies – stationery,Amount Not Matched
7,2025-05-30,-2500.0,REF487512,zomato food reimbursement,REF487512,2025-05-30,-2500,REF487512,zomato – team lunch,Amount Matched
8,NaT,NaN,NaN,NaN,REF159357,2025-05-31,-3000,REF159357,miscellaneous expense,Amount Not Matched

In [10]:
df1['Bank Description split']=df1['Bank Description'].str.split()
df1['GL Description split']=df1['GL Description'].str.split()
df1

,Date_bank,Bank Amount (INR),Bank Reference,Bank Description,Reference,Date_gl,GL Amount (INR),GL Reference,GL Description,Additional comments,Bank Description split,GL Description split
0,2025-05-01,50000.0,REF123456,salary credit,REF123456,2025-05-01,50000,REF123456,salary a/c – april,Amount Matched,"[salary, credit]","[salary, a/c, –, april]"
1,2025-05-03,-5000.0,REF345678,electricity bill - tata,REF345678,2025-05-03,-5000,REF345678,power utility - tata,Amount Matched,"[electricity, bill, -, tata]","[power, utility, -, tata]"
2,2025-05-05,-1200.0,REF120045,phone bill - airtel,REF120045,2025-05-05,-1250,REF120045,airtel recharge,Amount Not Matched,"[phone, bill, -, airtel]","[airtel, recharge]"
3,2025-05-08,-10000.0,REF784512,rent payment - may,REF784512,2025-05-08,-10000,REF784512,rent transfer for may,Amount Matched,"[rent, payment, -, may]","[rent, transfer, for, may]"
4,2025-05-15,75000.0,REF741258,client payment inv#205,REF741258,2025-05-15,75000,REF741258,client receipt – invoice 205,Amount Matched,"[client, payment, inv#205]","[client, receipt, –, invoice, 205]"
5,2025-05-21,-1500.0,REF698745,internet charges - act,REF698745,2025-05-21,-1500,REF698745,broadband – act fibernet,Amount Matched,"[internet, charges, -, act]","[broadband, –, act, fibernet]"
6,2025-05-25,-8000.0,REF963258,office supplies - staples,REF963258,2025-05-25,-7800,REF963258,supplies – stationery,Amount Not Matched,"[office, supplies, -, staples]","[supplies, –, stationery]"
7,2025-05-30,-2500.0,REF487512,zomato food reimbursement,REF487512,2025-05-30,-2500,REF487512,zomato – team lunch,Amount Matched,"[zomato, food, reimbursement]","[zomato, –, team, lunch]"
8,NaT,NaN,NaN,NaN,REF159357,2025-05-31,-3000,REF159357,miscellaneous expense,Amount Not Matched,NaN,"[miscellaneous, expense]"

In [11]:
s = ['salary', 'bill', 'rent', 'monthly', 'quarterly', 'yearly']
match =[]
for i in range(len(df1)):
    words = df1.loc[i, 'Bank Description split']  # Get the list from the column

    # isinstance usage to avoid errors when iterating through data where some entries may not be lists 
    # e.g., could be NaN, None, or a string
    if isinstance(words, list):
        # Go through each word in that list
        for word in words:
            if word in s:
                print(words)
                break  # No need to check further words if one match is found

['salary', 'credit']
['electricity', 'bill', '-', 'tata']
['phone', 'bill', '-', 'airtel']
['rent', 'payment', '-', 'may']

In [12]:
s = ['salary', 'bill', 'rent', 'monthly', 'quarterly', 'yearly']

# Create an empty list to store results
matches = []

# Loop through each row
for i in range(len(df1)):
    words = df1.loc[i, 'Bank Description split']  # get the value from the column

    found = None  # default: no match
    if isinstance(words, list):  # only check if it's actually a list
        for word in words:
            if word in s:
                found = word     # store the matched word
                break            # stop after first match
    
    matches.append(found)  # add result (word or None) to the list

# Add as a new column
df1["Matched Word"] = matches

In [13]:
df1

,Date_bank,Bank Amount (INR),Bank Reference,Bank Description,Reference,Date_gl,GL Amount (INR),GL Reference,GL Description,Additional comments,Bank Description split,GL Description split,Matched Word
0,2025-05-01,50000.0,REF123456,salary credit,REF123456,2025-05-01,50000,REF123456,salary a/c – april,Amount Matched,"[salary, credit]","[salary, a/c, –, april]",salary
1,2025-05-03,-5000.0,REF345678,electricity bill - tata,REF345678,2025-05-03,-5000,REF345678,power utility - tata,Amount Matched,"[electricity, bill, -, tata]","[power, utility, -, tata]",bill
2,2025-05-05,-1200.0,REF120045,phone bill - airtel,REF120045,2025-05-05,-1250,REF120045,airtel recharge,Amount Not Matched,"[phone, bill, -, airtel]","[airtel, recharge]",bill
3,2025-05-08,-10000.0,REF784512,rent payment - may,REF784512,2025-05-08,-10000,REF784512,rent transfer for may,Amount Matched,"[rent, payment, -, may]","[rent, transfer, for, may]",rent
4,2025-05-15,75000.0,REF741258,client payment inv#205,REF741258,2025-05-15,75000,REF741258,client receipt – invoice 205,Amount Matched,"[client, payment, inv#205]","[client, receipt, –, invoice, 205]",None
5,2025-05-21,-1500.0,REF698745,internet charges - act,REF698745,2025-05-21,-1500,REF698745,broadband – act fibernet,Amount Matched,"[internet, charges, -, act]","[broadband, –, act, fibernet]",None
6,2025-05-25,-8000.0,REF963258,office supplies - staples,REF963258,2025-05-25,-7800,REF963258,supplies – stationery,Amount Not Matched,"[office, supplies, -, staples]","[supplies, –, stationery]",None
7,2025-05-30,-2500.0,REF487512,zomato food reimbursement,REF487512,2025-05-30,-2500,REF487512,zomato – team lunch,Amount Matched,"[zomato, food, reimbursement]","[zomato, –, team, lunch]",None
8,NaT,NaN,NaN,NaN,REF159357,2025-05-31,-3000,REF159357,miscellaneous expense,Amount Not Matched,NaN,"[miscellaneous, expense]",None