In [3]:
import pandas as pd
import numpy as np

In [5]:
df=pd.read_csv('weather3.csv')
df

        date      city  temperature  humidity
0   5/1/2017  new york           65        56
1   5/2/2017  new york           61        54
2   5/3/2017  new york           70        60
3  12/1/2017  new york           30        50
4  12/2/2017  new york           28        52
5  12/3/2017  new york           25        51

In [7]:
type(df['date'][0])

str

# Convert string to dateformat for Date column

In [10]:
df['date']=pd.to_datetime(df['date'])

In [11]:
df

        date      city  temperature  humidity
0 2017-05-01  new york           65        56
1 2017-05-02  new york           61        54
2 2017-05-03  new york           70        60
3 2017-12-01  new york           30        50
4 2017-12-02  new york           28        52
5 2017-12-03  new york           25        51

# Group by month from date column use grouper. 
# Margin=True for GrandTotal not rquired in grouper as it already grouping as per months
Grouper is used in pandas and it needs 2 arguments- frequency i.e. occurence and key i.e. column

In [19]:
df.pivot_table(index=pd.Grouper(freq='M',key='date'),columns='city')

             humidity temperature
city         new york    new york
date
2017-05-31  56.666667   65.333333
2017-12-31  51.000000   27.666667