# In pivot, we can't aggregate or summarize the dataframe like pivot table

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('weather.csv')
df

       date      city  temperature  humidity
0  5/1/2017  new york           65        56
1  5/2/2017  new york           66        58
2  5/3/2017  new york           68        60
3  5/1/2017    mumbai           75        80
4  5/2/2017    mumbai           78        83
5  5/3/2017    mumbai           82        85
6  5/1/2017   beijing           80        26
7  5/2/2017   beijing           77        30
8  5/3/2017   beijing           79        35

In [4]:
new_pivot=df.pivot(index='date',columns='city')
new_pivot

         temperature                 humidity
city         beijing mumbai new york  beijing mumbai new york
date
5/1/2017          80     75       65       26     80       56
5/2/2017          77     78       66       30     83       58
5/3/2017          79     82       68       35     85       60

In [5]:
# Save the pivot table to an Excel file
with pd.ExcelWriter('pivot_creation.xlsx', engine='xlsxwriter') as writer:
    new_pivot.to_excel(writer, sheet_name='pivot1')
print('File downloaded')

File downloaded