In [23]:
import pandas as pd
import numpy as np

In [24]:
A ='old_month.xlsx'

# Reading the file

In [25]:
old=pd.read_excel(A)
old

,Imp,Fund_Imp,Fund_Description,Fund_Dept_ID,Fund_Dept_ID_Description,Approver_ID,Approver_Name,Proposed_Invoice_Approver,Team,Title,Threshold_USD
0,F000001,443045,European Retail Solutions,442003,COF III,103847,Jonathan_Cancrco,Jonathan_Cancrco,Finance,Director,"500,000"
1,F000002,445047,European Retail Solutions,442003,COF III,102362,Hart_Christopher,Limonpierre_Ian,Finance,Associate Director,"100,000"
2,F000003,443045,AlterI,442005,COF II,103322,Verderaime_Joseph,Parillis_Joseph_Anthony,Finance,Managing Director,">1,000,000"
3,F000004,443045,European Retail Solutions,442100,COF I,102353,Parillis_Joseph_Anthony,Shinde_Ashutosh,Finance,Director,">1,000,000"
4,F000005,442100,AOP II,443045,INACTIVE,103250,Hart_Christopher,Parillis_Joseph_Anthony,Finance,Associate Director,"100,000"
...,...,...,...,...,...,...,...,...,...,...,...
195,F000196,445047,Alter Invest Fund I,442003,COF I,102885,Shinde_Ashutosh,Limonpierre_Ian,Finance,Director,"500,000"
196,F000197,442003,AlterI,445047,COF II,103293,Jonathan_Cancrco,Masud_Shahid,Finance,Associate Director,"100,000"
197,F000198,443045,AlterI,442100,COF I,103401,Gaffney_Jocelyn_K,Shinde_Ashutosh,Finance,Managing Director,"250,000"
198,F000199,442005,AlterI,442005,COF III,102205,Parillis_Joseph_Anthony,Dallasykar_Ajay,Finance,Managing Director,">1,000,000"
199,F000200,442005,European Retail Solutions,445047,COF II,102481,Dallasykar_Ajay,Limonpierre_Ian,Finance,Principal,"500,000"

# Delete the whitespaces and make object datatype lowercase in file

In [26]:
for col in old.select_dtypes(include=[object]):
    old[col] = old[col].str.strip()

In [27]:
for col in old.select_dtypes(include=[object]):
    old[col] = old[col].str.lower()
old

,Imp,Fund_Imp,Fund_Description,Fund_Dept_ID,Fund_Dept_ID_Description,Approver_ID,Approver_Name,Proposed_Invoice_Approver,Team,Title,Threshold_USD
0,f000001,443045,european retail solutions,442003,cof iii,103847,jonathan_cancrco,jonathan_cancrco,finance,director,"500,000"
1,f000002,445047,european retail solutions,442003,cof iii,102362,hart_christopher,limonpierre_ian,finance,associate director,"100,000"
2,f000003,443045,alteri,442005,cof ii,103322,verderaime_joseph,parillis_joseph_anthony,finance,managing director,">1,000,000"
3,f000004,443045,european retail solutions,442100,cof i,102353,parillis_joseph_anthony,shinde_ashutosh,finance,director,">1,000,000"
4,f000005,442100,aop ii,443045,inactive,103250,hart_christopher,parillis_joseph_anthony,finance,associate director,"100,000"
...,...,...,...,...,...,...,...,...,...,...,...
195,f000196,445047,alter invest fund i,442003,cof i,102885,shinde_ashutosh,limonpierre_ian,finance,director,"500,000"
196,f000197,442003,alteri,445047,cof ii,103293,jonathan_cancrco,masud_shahid,finance,associate director,"100,000"
197,f000198,443045,alteri,442100,cof i,103401,gaffney_jocelyn_k,shinde_ashutosh,finance,managing director,"250,000"
198,f000199,442005,alteri,442005,cof iii,102205,parillis_joseph_anthony,dallasykar_ajay,finance,managing director,">1,000,000"
199,f000200,442005,european retail solutions,445047,cof ii,102481,dallasykar_ajay,limonpierre_ian,finance,principal,"500,000"

import xlsxwriter

with pd.ExcelWriter('Sorted.xlsx',engine='xlsxwriter') as writer:
    old.to_excel(writer,sheet_name='nowhitespace',index=False)
print("Downloaded")

# Delete the duplicate entries from the file

In [28]:
old=old.drop_duplicates()

# Adding extra column

In [29]:
old['source']='old file'

In [30]:
old

,Imp,Fund_Imp,Fund_Description,Fund_Dept_ID,Fund_Dept_ID_Description,Approver_ID,Approver_Name,Proposed_Invoice_Approver,Team,Title,Threshold_USD,source
0,f000001,443045,european retail solutions,442003,cof iii,103847,jonathan_cancrco,jonathan_cancrco,finance,director,"500,000",old file
1,f000002,445047,european retail solutions,442003,cof iii,102362,hart_christopher,limonpierre_ian,finance,associate director,"100,000",old file
2,f000003,443045,alteri,442005,cof ii,103322,verderaime_joseph,parillis_joseph_anthony,finance,managing director,">1,000,000",old file
3,f000004,443045,european retail solutions,442100,cof i,102353,parillis_joseph_anthony,shinde_ashutosh,finance,director,">1,000,000",old file
4,f000005,442100,aop ii,443045,inactive,103250,hart_christopher,parillis_joseph_anthony,finance,associate director,"100,000",old file
...,...,...,...,...,...,...,...,...,...,...,...,...
195,f000196,445047,alter invest fund i,442003,cof i,102885,shinde_ashutosh,limonpierre_ian,finance,director,"500,000",old file
196,f000197,442003,alteri,445047,cof ii,103293,jonathan_cancrco,masud_shahid,finance,associate director,"100,000",old file
197,f000198,443045,alteri,442100,cof i,103401,gaffney_jocelyn_k,shinde_ashutosh,finance,managing director,"250,000",old file
198,f000199,442005,alteri,442005,cof iii,102205,parillis_joseph_anthony,dallasykar_ajay,finance,managing director,">1,000,000",old file
199,f000200,442005,european retail solutions,445047,cof ii,102481,dallasykar_ajay,limonpierre_ian,finance,principal,"500,000",old file

# cleansing the new file with whitespaces deletion, lowercase and duplicate removal and adding new column

In [31]:
B ='current_month.xlsx'
new=pd.read_excel(B)
for col in new.select_dtypes(include=[object]):
    new[col] = new[col].str.strip()
for col in new.select_dtypes(include=[object]):
    new[col] = new[col].str.lower()
new=new.drop_duplicates()
new['source']='new file'
new

,Imp,Fund_Imp,Fund_Description,Fund_Dept_ID,Fund_Dept_ID_Description,Approver_ID,Approver_Name,Proposed_Invoice_Approver,Team,Title,Threshold_USD,source
0,f000096,442003,aop ii,443045,cof i,102065,gaffney_jocelyn_k,thakkar_ashish,finance,associate director,">1,000,000",new file
1,f000016,442005,european retail solutions,442005,cof iii,101858,thakkar_ashish,limonpierre_ian,finance,director,">1,000,000",new file
2,f000031,442005,aop ii,442100,cof ii,103340,verderaime_joseph,gaffney_jocelyn_k,finance,director,"100,000",new file
3,f000159,443045,alter invest fund i,443045,inactive,103585,verderaime_joseph,jonathan_cancrco,finance,principal,"250,000",new file
4,f000129,442005,european retail solutions,445047,cof iii,102137,limonpierre_ian,dallasykar_ajay,finance,principal,">1,000,000",new file
...,...,...,...,...,...,...,...,...,...,...,...,...
175,f000375,443045,aop ii,442003,inactive,101667,dallasykar_ajay,jonathan_cancrco,finance,associate director,"500,000",new file
176,f000376,443045,alteri,442100,cof iii,103711,limonpierre_ian,parillis_joseph_anthony,finance,principal,"100,000",new file
177,f000377,442003,alter invest fund i,442003,cof iii,102100,parillis_joseph_anthony,gaffney_jocelyn_k,finance,associate director,">1,000,000",new file
178,f000378,443045,aop ii,442003,cof iii,102924,shinde_ashutosh,limonpierre_ian,finance,principal,">1,000,000",new file
179,f000379,443045,european retail solutions,442003,aop ii,101042,parillis_joseph_anthony,parillis_joseph_anthony,finance,associate director,"250,000",new file

# Select few columns for concat

In [33]:
cols=['Imp','Fund_Imp','Fund_Dept_ID','Approver_ID','Proposed_Invoice_Approver','Title','Threshold_USD','source']

In [34]:
combined=pd.concat([old[cols],new[cols]])
combined

,Imp,Fund_Imp,Fund_Dept_ID,Approver_ID,Proposed_Invoice_Approver,Title,Threshold_USD,source
0,f000001,443045,442003,103847,jonathan_cancrco,director,"500,000",old file
1,f000002,445047,442003,102362,limonpierre_ian,associate director,"100,000",old file
2,f000003,443045,442005,103322,parillis_joseph_anthony,managing director,">1,000,000",old file
3,f000004,443045,442100,102353,shinde_ashutosh,director,">1,000,000",old file
4,f000005,442100,443045,103250,parillis_joseph_anthony,associate director,"100,000",old file
...,...,...,...,...,...,...,...,...
175,f000375,443045,442003,101667,jonathan_cancrco,associate director,"500,000",new file
176,f000376,443045,442100,103711,parillis_joseph_anthony,principal,"100,000",new file
177,f000377,442003,442003,102100,gaffney_jocelyn_k,associate director,">1,000,000",new file
178,f000378,443045,442003,102924,limonpierre_ian,principal,">1,000,000",new file
179,f000379,443045,442003,101042,parillis_joseph_anthony,associate director,"250,000",new file

# Matched entries in both the files with source file name

In [36]:
Values_found_in_both=combined[combined.duplicated(subset=[col for col in combined.columns if col != 'source'],keep=False)] # False is used to keep matched records in both files
Values_found_in_both

,Imp,Fund_Imp,Fund_Dept_ID,Approver_ID,Proposed_Invoice_Approver,Title,Threshold_USD,source
2,f000003,443045,442005,103322,parillis_joseph_anthony,managing director,">1,000,000",old file
5,f000006,443045,445047,101288,dallasykar_ajay,principal,"100,000",old file
6,f000007,443045,443045,101559,shinde_ashutosh,managing director,"100,000",old file
9,f000010,445047,445047,103582,gaffney_jocelyn_k,associate director,"100,000",old file
11,f000012,442100,445047,101723,verderaime_joseph,associate director,"100,000",old file
...,...,...,...,...,...,...,...,...
95,f000195,442005,442003,101886,hart_christopher,associate director,"100,000",new file
96,f000160,443045,443045,101379,parillis_joseph_anthony,managing director,"100,000",new file
97,f000007,443045,443045,101559,shinde_ashutosh,managing director,"100,000",new file
98,f000028,442003,442100,101925,masud_shahid,principal,"100,000",new file
99,f000121,445047,443045,103693,pinto_miguel_anthony,managing director,"250,000",new file

# Values found only in new and only in old