In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_excel('Sample1.xlsx')
df.head()

,Fiscal Quarter ID,Fiscal Period ID,Sales Level 1,Sales Level 2,Sales Level 3,Internal Business Entity Description,Internal Sub Business Entity Description,Corporate Bookings Flag,Organization Code,Technology Group,...,Product Classification,Software Type,Revenue Recognition Flag,Accounting Rule,Product Family,Txn Net Price Indicator,XCAT Flag,Business Model,Org Category,Product Bookings Net
0,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Perpetual,Y,NaN,HCIPPSW,=,N,Physical Delivery,Adj. Org,-80.06
1,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Hardware,On-Premise Subscription,Y,NaN,UCSHX,=,N,Physical Delivery,Adj. Org,-10774.67
2,2025Q2,202503,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HCIPS,=,N,Non Factory,Adj. Org,-754.32
3,2025Q2,202501,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HCISW,=,N,Non Factory,Adj. Org,-9439.98
4,2025Q2,202502,Americas,AMERICAS_MISC,AMERICAS MISC CONTRA L3,Cisco Compute,Hyper Converged,Y,-,CSPTG,...,Software,On-Premise Subscription,Y,NaN,HXDP,=,N,Non Factory,Adj. Org,-38.30

# to avoid warnings in the code

In [6]:
import warnings
warnings.filterwarnings('ignore')

# Pivot table created with 1st condition

In [8]:
p1=pd.pivot_table(df,columns=['Fiscal Quarter ID','Fiscal Period ID'],index='Business Model',values='Product Bookings Net',aggfunc=sum)
p1

Fiscal Quarter ID    2025Q2
Fiscal Period ID     202501    202502     202503
Business Model
Non Factory        -9571.57 -36561.22 -199443.97
Physical Delivery -25347.97 -54631.96  -32887.53
XCAT-MSJ           -1306.01       NaN        NaN

In [13]:
p2=pd.pivot_table(df,columns=['Fiscal Quarter ID','Fiscal Period ID'],index='Business Model',values='Product Bookings Net',aggfunc=sum)
p2

Fiscal Quarter ID    2025Q2
Fiscal Period ID     202501    202502     202503
Business Model
Non Factory        -9571.57 -36561.22 -199443.97
Physical Delivery -25347.97 -54631.96  -32887.53
XCAT-MSJ           -1306.01       NaN        NaN

filtered_data_1 = df[df['Txn Net Price Indicator'].isin(['=', 'Y'])& df['Corporate Bookings Flag']=='Y']

In [18]:
filtered_p2=p2.where(df['Bookings Adjustments Type'].isin(['BOOKING', '(blank)'])& df['Corporate Bookings Flag']=='Y')
filtered_p2

Fiscal Quarter ID 2025Q2
Fiscal Period ID  202501 202502 202503
Business Model
Non Factory          NaN    NaN    NaN
Physical Delivery    NaN    NaN    NaN
XCAT-MSJ             NaN    NaN    NaN