In [120]:
import pandas as pd
import numpy as np

# Read the excel file

In [121]:
df=pd.read_excel('Input.xlsx')
df.head()

,Fiscal Quarter ID,Fiscal Period ID,Corporate Bookings Flag,Organization Code,Bookings Adjustments Type,Bookings Adjustments Code,Delivery Option Code,Monetization,Product Category,Product Classification,Software Type,Revenue Recognition Flag,Accounting Rule,Product Family,Txn Net Price Indicator,XCAT Flag,Business Model,Org Category,Product Bookings Net
0,2025Q2,202504,Y,-,BOOKING,RB,UNKNOWN,Perpetual,Software,Software,On-Premise Perpetual,Y,NaN,HCIPPSW,=,N,Physical Delivery,Adj. Org,-80.06
1,2025Q2,202504,Y,-,BOOKING,RB,UNKNOWN,Term,Hardware,Hardware,On-Premise Subscription,Y,NaN,UCSHX,=,N,Physical Delivery,Adj. Org,-10774.67
2,2025Q2,202504,Y,-,BOOKING,RB,UNKNOWN,Term,Software,Software,On-Premise Subscription,Y,NaN,HCIPS,=,N,Non Factory,Adj. Org,-754.32
3,2025Q2,202504,Y,-,BOOKING,RB,UNKNOWN,Term,Software,Software,On-Premise Subscription,Y,NaN,HCISW,=,N,Non Factory,Adj. Org,-9439.98
4,2025Q2,202504,Y,-,BOOKING,RB,UNKNOWN,Term,Software,Software,On-Premise Subscription,Y,NaN,HXDP,=,N,Non Factory,Adj. Org,-38.30

# Check the datatype of all the columns

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147359 entries, 0 to 147358
Data columns (total 19 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Fiscal Quarter ID          147359 non-null  object
 1   Fiscal Period ID           147359 non-null  int64
 2   Corporate Bookings Flag    147359 non-null  object
 3   Organization Code          147359 non-null  object
 4   Bookings Adjustments Type  97553 non-null   object
 5   Bookings Adjustments Code  147359 non-null  object
 6   Delivery Option Code       147359 non-null  object
 7   Monetization               147359 non-null  object
 8   Product Category           147359 non-null  object
 9   Product Classification     147359 non-null  object
 10  Software Type              147359 non-null  object
 11  Revenue Recognition Flag   147359 non-null  object
 12  Accounting Rule            123455 non-null  object
 13  Product Family             147359 non-null  object
 14  Txn Net Price Indicator    147359 non-null  object
 15  XCAT Flag                  147359 non-null  object
 16  Business Model             147359 non-null  object
 17  Org Category               147359 non-null  object
 18  Product Bookings Net       147359 non-null  float64
dtypes: float64(1), int64(1), object(17)
memory usage: 21.4+ MB

# Check if any column has NaN value

In [123]:
df.isna().any()

Fiscal Quarter ID            False
Fiscal Period ID             False
Corporate Bookings Flag      False
Organization Code            False
Bookings Adjustments Type     True
Bookings Adjustments Code    False
Delivery Option Code         False
Monetization                 False
Product Category             False
Product Classification       False
Software Type                False
Revenue Recognition Flag     False
Accounting Rule               True
Product Family               False
Txn Net Price Indicator      False
XCAT Flag                    False
Business Model               False
Org Category                 False
Product Bookings Net         False
dtype: bool

# Checked the NaN column

In [124]:
df['Bookings Adjustments Type']

0              BOOKING
1              BOOKING
2              BOOKING
3              BOOKING
4              BOOKING
              ...
147354             NaN
147355             NaN
147356             NaN
147357    DSV Bookings
147358    DSV Bookings
Name: Bookings Adjustments Type, Length: 147359, dtype: object

# to avoid warnings in the code

In [125]:
import warnings
warnings.filterwarnings('ignore')

# Pivot table created with 1st condition

In [126]:
p1=pd.pivot_table(df,columns=['Fiscal Quarter ID','Fiscal Period ID'],index='Business Model',values='Product Bookings Net',aggfunc=sum)
p1

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic         2.208989e+07
NON FACTORY        2.395364e+07
Non Factory        6.446795e+08
Physical Delivery  1.459114e+09
Traditional MSJ    1.259692e+08
XCAT-MSJ          -1.739578e+06

In [127]:
p2=pd.pivot_table(df,columns=['Fiscal Quarter ID','Fiscal Period ID'],index='Business Model',values='Product Bookings Net',aggfunc=sum)
p2

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic         2.208989e+07
NON FACTORY        2.395364e+07
Non Factory        6.446795e+08
Physical Delivery  1.459114e+09
Traditional MSJ    1.259692e+08
XCAT-MSJ          -1.739578e+06

In [128]:
filtered_df = df[(df['Corporate Bookings Flag'] == 'Y')]
pcbf = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
pcbf

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic         2.009183e+07
NON FACTORY        2.396806e+07
Non Factory        6.507856e+08
Physical Delivery  1.428273e+09
Traditional MSJ    1.120785e+08
XCAT-MSJ          -1.739578e+06

In [129]:
filtered_df = df[(df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type']=='BOOKING')]
pbat = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
pbat

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic        -3.636784e+05
NON FACTORY       -3.577211e+05
Non Factory       -5.905929e+07
Physical Delivery -1.246890e+08
Traditional MSJ   -5.633781e+06
XCAT-MSJ          -6.487917e+07

In [130]:
filtered_df =df[df['Bookings Adjustments Type']=='BOOKING']
                
p3 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p3

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic        -4.266263e+05
NON FACTORY       -3.577211e+05
Non Factory       -6.346568e+07
Physical Delivery -3.048749e+08
Traditional MSJ   -6.830487e+06
XCAT-MSJ          -6.487917e+07

# Remove lead and trail space from the column

In [131]:
df['Bookings Adjustments Type'] = df['Bookings Adjustments Type'].str.strip()
df['Bookings Adjustments Type']

0              BOOKING
1              BOOKING
2              BOOKING
3              BOOKING
4              BOOKING
              ...
147354             NaN
147355             NaN
147356             NaN
147357    DSV Bookings
147358    DSV Bookings
Name: Bookings Adjustments Type, Length: 147359, dtype: object

# Convert NaN to 0 for the specific column

In [132]:
df['Bookings Adjustments Type'] = df['Bookings Adjustments Type'].fillna(0)
df['Bookings Adjustments Type']

0              BOOKING
1              BOOKING
2              BOOKING
3              BOOKING
4              BOOKING
              ...
147354               0
147355               0
147356               0
147357    DSV Bookings
147358    DSV Bookings
Name: Bookings Adjustments Type, Length: 147359, dtype: object

# Filter conditions to check the Booking Adjustment Type== 0

In [133]:
filtered_df =df[df['Bookings Adjustments Type']==0]
                
p3 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p3

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         2.251651e+07
NON FACTORY        2.431136e+07
Non Factory        7.081452e+08
Physical Delivery  1.763989e+09
Traditional MSJ    1.327997e+08
XCAT-MSJ           6.313960e+07

# FILTER-1 to 5

In [134]:
filtered_df = df[(df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type']=='BOOKING') |
                (df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type']==0)]
                 
p4 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p4

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic         1.483513e+07
NON FACTORY        2.396795e+07
Non Factory        4.815038e+08
Physical Delivery  8.726054e+08
Traditional MSJ    7.331381e+07
XCAT-MSJ          -1.739578e+06

In [135]:
df['Business Model'].unique()

array(['Physical Delivery', 'Non Factory', 'XCAT-MSJ', 'Traditional MSJ',
       'Electronic', 'NON FACTORY', 'Acquisition'], dtype=object)

# FILTER 6 to 8- 2 tier DSV LPOS WPL

In [90]:
df['Txn Net Price Indicator'].unique()

array(['=', 'Y', 'N'], dtype=object)

In [102]:
c1=['DSV Bookings',0] # list created with conditions for df['Bookings Adjustments Type']

filtered_df = df[(df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type'].isin(c1)) & (df['Txn Net Price Indicator']=='N')] 

p5 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p5

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Non Factory        13129.363815
Physical Delivery  12013.800000

# FILTER-2tierposnet

In [103]:
c1=['DSV Bookings',0] # list created with conditions for df['Bookings Adjustments Type']

filtered_df = df[(df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type'].isin(c1)) & (df['Txn Net Price Indicator']=='Y')] 

p6 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p6

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         5.281116e+06
NON FACTORY        1.041000e+02
Non Factory        2.416523e+08
Physical Delivery  3.069339e+08
Traditional MSJ    3.905091e+07

# FILTER-stdfctrnet

In [104]:

filtered_df = df[(df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type']=='BOOKING')]
p7 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p7

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic        -3.636784e+05
NON FACTORY       -3.577211e+05
Non Factory       -5.905929e+07
Physical Delivery -1.246890e+08
Traditional MSJ   -5.633781e+06
XCAT-MSJ          -6.487917e+07

# FILTER-stdfacgrosbkg

In [105]:
filtered_df = df[(df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type']==0)]
p8 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p8

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         1.519881e+07
NON FACTORY        2.432568e+07
Non Factory        5.405631e+08
Physical Delivery  9.972944e+08
Traditional MSJ    7.894759e+07
XCAT-MSJ           6.313960e+07

# FILTER-stdnonfacgros

In [106]:
c1=['BOOKING',0] # list created with conditions for df['Bookings Adjustments Type']

filtered_df = df[(df['Corporate Bookings Flag'] == 'Y') & (df['Bookings Adjustments Type'].isin(c1))] 

p9 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p9

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Acquisition        3.977391e+08
Electronic         1.483513e+07
NON FACTORY        2.396795e+07
Non Factory        4.815038e+08
Physical Delivery  8.726054e+08
Traditional MSJ    7.331381e+07
XCAT-MSJ          -1.739578e+06

# FILTER-2tierfactorynetbookingwpl

In [107]:
c1=['BOOKING',0] # list created with conditions for df['Bookings Adjustments Type']
c2=['=','N'] # List created with conditions for df['Txn Net Price Indicator']

filtered_df = df[(df['Corporate Bookings Flag'] == 'N') & (df['Bookings Adjustments Type'].isin(c1)) & (df['Txn Net Price Indicator'].isin(c2))] 

p10 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p10

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         5.235159e+05
Non Factory        1.746822e+06
Physical Delivery  1.626274e+08
Traditional MSJ   -6.191227e+04

# FILTER-2-Tier Factory Net (net price)

In [108]:
c1=['BOOKING',0] # list created with conditions for df['Bookings Adjustments Type']


filtered_df = df[(df['Corporate Bookings Flag'] == 'N') & (df['Bookings Adjustments Type'].isin(c1)) & (df['Txn Net Price Indicator']=='Y')] 

p11 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p11

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         6.731241e+06
NON FACTORY       -1.431888e+04
Non Factory        1.614289e+08
Physical Delivery  4.238811e+08
Traditional MSJ    5.271730e+07

# FILTER-2-Tier Factory, NTG (WPL)

In [109]:
c2=['=','N'] # List created with conditions for df['Txn Net Price Indicator']


filtered_df = df[(df['Corporate Bookings Flag'] == 'N') & (df['Bookings Adjustments Type']=='BOOKING') & (df['Txn Net Price Indicator'].isin(c2))] 

p12 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p12

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic        -2.914500e+02
Non Factory       -3.602419e+06
Physical Delivery -1.708401e+08
Traditional MSJ   -7.338030e+04

# FILTER- 2-Tier Factory NTG Bookingsnet

In [110]:
filtered_df = df[(df['Corporate Bookings Flag'] == 'N') & (df['Bookings Adjustments Type']=='BOOKING') & (df['Txn Net Price Indicator']=='Y')] 

p13 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p13

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic        -6.265643e+04
Non Factory       -8.039666e+05
Physical Delivery -9.345785e+06
Traditional MSJ   -1.123325e+06

# FILTER- 2-Tier Factory, Gross (WPL)

In [111]:
c2=['=','N'] # List created with conditions for df['Txn Net Price Indicator']


filtered_df = df[(df['Corporate Bookings Flag'] == 'N') & (df['Bookings Adjustments Type']==0) & (df['Txn Net Price Indicator'].isin(c2))] 

p14 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p14

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         5.238074e+05
Non Factory        5.349241e+06
Physical Delivery  3.334675e+08
Traditional MSJ    1.146803e+04

# FILTER-2-Tier NonFactory, Gross (WPL)

In [112]:
c1=['BOOKING',0] # list created with conditions for df['Bookings Adjustments Type']
c2=['=','N'] # List created with conditions for df['Txn Net Price Indicator']

filtered_df = df[(df['Corporate Bookings Flag'] == 'N') & (df['Bookings Adjustments Type'].isin(c1)) & (df['Txn Net Price Indicator'].isin(c2))] 

p15 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p15

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         5.235159e+05
Non Factory        1.746822e+06
Physical Delivery  1.626274e+08
Traditional MSJ   -6.191227e+04

# FILTER-2-Tier Factory & Non-Factory Gross (net price)

In [113]:
filtered_df = df[(df['Corporate Bookings Flag'] == 'N') & (df['Bookings Adjustments Type']==0) & (df['Txn Net Price Indicator']=='Y')] 

p16 = pd.pivot_table(filtered_df, 
                    columns=['Fiscal Quarter ID', 'Fiscal Period ID'], 
                    index='Business Model', 
                    values='Product Bookings Net', 
                    aggfunc=sum)
p16

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Electronic         6.793897e+06
NON FACTORY       -1.431888e+04
Non Factory        1.622328e+08
Physical Delivery  4.332269e+08
Traditional MSJ    5.384063e+07

In [118]:
p16.loc[['Physical Delivery','Traditional MSJ']] # pass 2D array for dataframe

Fiscal Quarter ID        2025Q2
Fiscal Period ID         202504
Business Model
Physical Delivery  4.332269e+08
Traditional MSJ    5.384063e+07

# Pending Tasks:
# how to filter index or rows- to select values under 'Business Model'- use loc method
# Fix the Non-Factory and NON FACTORY under 'Business Model'
# Map the excel outputs with the script output and naming convention
# Export to excel